#
# isort configuration
#   https://pycqa.github.io/isort/docs/configuration/options.html
#
[tool.isort]
py_version = 38
line_length = 120
lines_after_imports = 2
multi_line_output = 9
# See possible "multi_line_output" values at https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html
ensure_newline_before_comments = true
# Specify known_first_party if isort confuses first party modules for being something else
known_first_party = ""
known_local_folder = ""

#
# black configuration
#  https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format
#
[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = ''

#
# ruff configuration
#   https://beta.ruff.rs/docs/configuration/#using-pyprojecttoml
#
[tool.ruff]
line-length = 120
target-version = "py38"

# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "F", "W", "B"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
# fixable = [""]
unfixable = ["W", "B"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}
